java.net.preferIPv4Stack: true
spring:
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.lipzigg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0?ssl=false
      database: saveLink
      auto-index-creation: true
      ssl:
        enabled: false